//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BongDownloadConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording
    {
        public Recording()
        {
            this.RecordingFiles = new HashSet<RecordingFile>();
        }
    
        public int RecordingId { get; set; }
        public string BongRecordingId { get; set; }
        public string BongBroadcastId { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string ShortText { get; set; }
        public string LongText { get; set; }
        public string Country { get; set; }
        public string ProductionYear { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string BongChannelId { get; set; }
        public string BongChannelName { get; set; }
        public string Quality { get; set; }
        public string SerieId { get; set; }
        public string SerieSeason { get; set; }
        public string SerieEpisode { get; set; }
        public string SerieEpisodeCount { get; set; }
        public ProcessingStateEnum ProcessingState { get; set; }
    
        public virtual ICollection<RecordingFile> RecordingFiles { get; set; }
    }
}
