//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BongDownloadConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordingFile
    {
        public int RecordingFileId { get; set; }
        public int RecordingId { get; set; }
        public string FileType { get; set; }
        public string DownloadUrl { get; set; }
        public string Quality { get; set; }
        public ProcessingStateEnum ProcessingState { get; set; }
    
        public virtual Recording Recording { get; set; }
    }
}
